# Configuration ReadTheDocs pour Faso Arzeka Payment
version: 2

# Configuration du build
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Configuration Sphinx
sphinx:
  configuration: docs_sphinx/conf.py
  fail_on_warning: false

# Formats de sortie
formats:
  - pdf
  - epub

# Installation des dépendances Python
python:
  install:
    - requirements: docs_sphinx/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
